### ISSUE TITLE
k2p 怎么默认开启wifi?

### ISSUE THREAD

**Issue by dunmengjun** [garypang13/OpenWrt_x86-r2s-r4s-Rpi#419]
最新版本的系统，重启路由器后(不是更新系统哈，是执行重启或者断电重启)，wifi需要手动启动。这太麻烦了，有没有办法让wifi跟着系统启动一起启动？

**Comment by garypang13** [comment]
@dunmengjun 刷回老版本, https://op.supes.top/firmware/phicomm-k2p/

**Comment by dunmengjun** [comment]
@garypang13 05.05-openwrt-ramips-mt7621-phicomm_k2p-squashfs-sysupgrade.bin 这个行吗？

**Comment by garypang13** [comment]
@dunmengjun 可以
